# .Net Initialization

parameters:
  - name: BuildConfiguration
    type: string
    default: $(BuildConfiguration)
  - name: BuildParameters
    type: string
    default: Platform="$(BuildPlatform)"
steps:
  - task: NuGetAuthenticate@1
    displayName: NuGet Authenticate
  - task: UseDotNet@2
    displayName: Use .NET SDK from global.json
    inputs:
      useGlobalJson: true
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: "**\\*.sln"
      restoreArguments: /p:Configuration="${{parameters.BuildConfiguration}}" -p:${{parameters.BuildParameters}}
      feedRestore: Office
      includeNuGetOrg: false
