//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1570, 1587, 1696
namespace Microsoft.Omex.CodeGenerators.GateGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Omex.CodeGenerators.GateGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}/// &lt;summary&gt;
        ///{2}/// Name of the {0} gate.
        ///{2}/// &lt;/summary&gt;
        ///{2}public const string {0}GateName = &quot;{1}&quot;;
        ///
        ///
        ///{2}/// &lt;summary&gt;
        ///{2}/// Instance of the {0} gate.
        ///{2}/// &lt;/summary&gt;
        ///{2}private static IGate s_{0}Gate = new CachedGate({0}GateName);
        ///
        ///
        ///{2}/// &lt;summary&gt;
        ///{2}/// Instance of the {0} gate.
        ///{2}/// &lt;/summary&gt;
        ///{2}public static IGate {0}
        ///{2}{{
        ///{2}	get
        ///{2}	{{
        ///{2}		return s_{0}Gate;
        ///{2}	}}
        ///{2}}}
        ///.
        /// </summary>
        internal static string GatePropertyTemplate {
            get {
                return ResourceManager.GetString("GatePropertyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        ///// This code was generated by a tool.
        ///// Runtime Version:{1}
        /////
        ///// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///// Copyright (c) Microsoft Corporation
        ///
        ///using System.CodeDom.Compiler;
        ///using System.Diagnostics;
        ///using System.Runtime.CompilerServices; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GatesClassTemplate {
            get {
                return ResourceManager.GetString("GatesClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/// &lt;summary&gt;
        ///{0}/// {1} gates
        ///{0}/// &lt;/summary&gt;
        ///{0}public static class {1}
        ///{0}{{
        ///{2}{0}}}
        ///.
        /// </summary>
        internal static string NestingTemplate {
            get {
                return ResourceManager.GetString("NestingTemplate", resourceCulture);
            }
        }
    }
}
#pragma warning restore 1570, 1587, 1696
