name: Build and run unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # [ubuntu-latest, windows-latest, macOS-latest]
        configuration: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build --configuration ${{ matrix.configuration }}
    - name: Run Unit Tests
      run: dotnet test --no-build --configuration ${{ matrix.configuration }}
    - name: Create NuGet packages
      run: dotnet pack --no-build --configuration ${{ matrix.configuration }}
